[package]
org = "WSO2"
name = "channel_service"
version = "1.0.0"
export = ["channel_service"]
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "pubudu538"
name = "choreo.user.info"
version = "0.1.1"